### ISSUE TITLE
a working solution, please

### ISSUE THREAD

**Issue by UnrulyNatives** [igaster/laravel-theme#1]
Hi, 
your package is extremely promising, however as an amateur programmer I got lost when trying to implement a theme switch button.

Can I hope for a example solution in your docs? 

Thx, 

Peter

http://stackoverflow.com/questions/29025983/themes-with-package-igaster

**Comment by igaster** [comment]
This is a sample service provider:
 
```php
    class myServiceProvider extends ServiceProvider {
        public function register()
        {
            \Theme::set(\Cookie::get('themeName'));
        }
    }
```
To enable it you should add it in your `Providers` array (in `app.php`)

now your route could be something like:
```php
    Route::get('set_theme/{themeName}', function($themeName){

        if (Theme::find($themeName)) // Is $themeName valid?
            Coockie::forever('themeName', $themeName);

        Redirect::url('/');
    });
```
Not best-practices but gives you an idea...

**Comment by igaster** [comment]
Since Sessions in Laravel5 are initiated in the middleware stack you should create your own middleware and place it in the `$middleware` array in `Kernel.php`. This is a sample middleware:  

    class myMiddleware {
        public function handle($request, Closure $next) {

           $themeName = \Session::get('themeName', 'NONE');

              if(\Theme::exists($themeName))
                  \Theme::set($themeName);

               return $next($request);
           }

       }


your routes.php could be something like:  

    Route::get('setTheme/{themeName}', function($themeName){
        Session::put('themeName', $themeName);
        return Redirect::to('/');
    });

    Route::get('/', function() {
        return Theme::get();  // display your views here....
    });
