### ISSUE TITLE
can u give sample for Defining themes

### ISSUE THREAD

**Issue by rayhan0421** [igaster/laravel-theme#10]

**Comment by igaster** [comment]
eg suppose that you have a landing page (themeLanding) and two themes (theme1 & theme2) based on bootstrap. Let theme1 and theme2 share some views and some asset (eg bootstrap.css) while themeLanding is completely different... This is a propossed configuration:

```php
'themes' => [
	'themeShared',
	'themeLandingPage',

	'theme1' 		=> [
		'extends' => 'themeShared',
	],

	'theme2' 		=> [
		'extends' => 'themeShared',
	],
]
```
and your folder structure: 
```
resources
    +--views
         +--themeShared
         +--themeLanding
         +--theme1
         +--theme2
```

The same structure can be followed in your public folder to seperate your assets...

**Comment by rayhan0421** [comment]
thank u
