### ISSUE TITLE
 Set theme in controller not work

### ISSUE THREAD

**Issue by macagoraga** [igaster/laravel-theme#100]
If I try to set theme in controller then it not work.

    public function __construct()
    {
        \Theme::set('custom');
        dd(\Theme::current()); // Return correctly custom theme info but load default
    }

If I setup via config globally then work fine

**Comment by macagoraga** [comment]
I found here similar issue: https://github.com/igaster/laravel-theme/issues/87

I see you do a push here for fix this:
https://github.com/igaster/laravel-theme/commit/31cab14baf75c6f38b5e1df5a4937885728c70a2

Version that I use don't have this push, I am using 

igaster/laravel-theme                 v2.0.9

which should be last

**Comment by macagoraga** [comment]
Adding $themeViewFinder->flushFinderCache(); like in your push, get blank page.. themeViewFinder not found,

**Comment by igaster** [comment]
@macagoraga I don't think these two issues are related... Maybe the problem is that you are setting the theme in the constructor... and then some other code will change it to default...

If you try to set it in your controller method, will it fail again??
