### ISSUE TITLE
 LogicException  : Choice question must have at least 1 choice available

### ISSUE THREAD

**Issue by kjareena** [igaster/laravel-theme#103]
**php artisan theme:install**
if i used this command it getting below error.

LogicException : Choice question must have at least 1 choice available.

**at E:\wamp64\www\bharosa\vendor\symfony\console\Question\ChoiceQuestion.php:36
32**
i have created two themes using create command

**php artisan theme:list**
+----------------------+----------------------+----------------------+----------------------+
| Theme Name | Extends | Views Path | Asset Path |
+----------------------+----------------------+----------------------+----------------------+
| admin | | admin | admin |
| website | | website | website |
+----------------------+----------------------+----------------------+----------------------+
Views Path is relative to: \resources\views
Asset Path is relative to: \public

please help me

**Comment by kjareena** [comment]
**php artisan theme:install**
if i used this command it getting below error.


  LogicException  : Choice question must have at least 1 choice available.

 at E:\wamp64\www\bharosa\vendor\symfony\console\Question\ChoiceQuestion.php:36
   32|      */
i have created two themes using create command

>php artisan theme:list
+----------------------+----------------------+----------------------+----------------------+
|      Theme Name      |        Extends       |      Views Path      |      Asset Path      |
+----------------------+----------------------+----------------------+----------------------+
| admin                |                      | admin                | admin                |
| website              |                      | website              | website              |
+----------------------+----------------------+----------------------+----------------------+
Views Path is relative to: \resources\views
Asset Path is relative to: \public


please help me

**Comment by igaster** [comment]
This command is used to install some theme that you have packaged with `artisan theme:package` command

Probably there are no theme packages so you get this error (BTW I should fix this anyway)

If you just created the themes with `theme:create` then you don't have to install them!
