### ISSUE TITLE
only loading default view page

### ISSUE THREAD

**Issue by rayhan0421** [igaster/laravel-theme#11]
i make theme1 in view folder and put my blade file on there . but it only loading from view/index.blade.php not loading from view/theme1/index.blade.php

asset is working nice like js css img

**Comment by igaster** [comment]
just some checkout:
- have you `Theme::set('theme1');` before rendering your view?
- does file `resources\views\theme1\index.blade.php` exists? If not then it is normal to fallback to the default path.

**Comment by rayhan0421** [comment]
i set theme on middleware

**Comment by rayhan0421** [comment]
view file exist

**Comment by igaster** [comment]
Ok. some debbuing:

in your controller file, just before returning your View try to `dd(\Config::get('view.paths'));`. This will return the search path for your views. `.../resources/views/theme1` should be before `.../resources/views`

**Comment by rayhan0421** [comment]
output
 array:2 [▼
  0 => "C:\xampp\htdocs\bdfreedom\resources\views/t1"
  1 => "C:\xampp\htdocs\bdfreedom\resources\views"
]

**Comment by rayhan0421** [comment]
for {{ Theme::js('js/readmore.js') 

output is <script src="/t1/js/readmore.js">

**Comment by igaster** [comment]
It seems that there is an error in your configuration file. You have something like:

```php
		'theme1' => [
			'views-path' 	=> 't1',
			],
		],
```
Change to 
```php
		'theme1' => [
			'views-path' 	=> 'theme1',
			],
		],
```
(or you can ommit any configuration for theme1 if you are using the defaults)

**Comment by rayhan0421** [comment]
this is theme.php
<?php

return [

	/*
	|--------------------------------------------------------------------------
	| Switch this package on/off. Usefull for testing...
	|--------------------------------------------------------------------------
	*/

	'enabled' => true,

	/*
	|--------------------------------------------------------------------------
	| Set behavior if an asset is not found in a Theme hierarcy.
	| Available options: THROW_EXCEPTION | LOG_ERROR | IGNORE
	|--------------------------------------------------------------------------
	*/

	'asset_not_found' => 'LOG_ERROR',

	/*
	|--------------------------------------------------------------------------
	| Set the Active Theme. Can be set at runtime with:
	|  Themes::set('theme-name');
	|--------------------------------------------------------------------------
	*/

	'active' => 'default',

	/*
	|--------------------------------------------------------------------------
	| Define available themes. Format:
	|
	| 	'theme-name' => [
	| 		'extends'	 	=> 'theme-to-extend',  // optional
	| 		'views-path' 	=> 'path-to-views',    // defaults to: resources/views/theme-name
	| 		'asset-path' 	=> 'path-to-assets',   // defaults to: public/theme-name
    |
    |		// you can add your own custom keys and retrieve them with Theme::config('key');
	| 	],
	|
	|--------------------------------------------------------------------------
	*/

	'themes' => [

		'default' => [
			'extends'	 	=> null,
			'views-path' 	=> '',
			'asset-path' 	=> '',
		],

		// Add your themes here...
		't1',
		't2',
		
		

		/*--------------[ Example Structre ]-------------

			// Recomended (all defaults) : Assets -> \public\BasicTheme , Views -> \resources\views\BasicTheme

			'BasicTheme',


			// This theme shares the views with BasicTheme but defines its own assets in \public\SomeTheme

			'SomeTheme' => [
				'views-path'	=> 'BasicTheme',
			],


			// This theme extends BasicTheme and ovverides SOME views\assets in its folders

			'AnotherTheme' => [
				'extends'	=> 'BasicTheme',
			],

		------------------------------------------------*/
	],

];

**Comment by rayhan0421** [comment]
i am not using theme1

**Comment by rayhan0421** [comment]
i made t1 and t2 into public and resource

**Comment by igaster** [comment]
For some reason you are setting somewhere the active theme to 't1' and not 'theme1'. Try to `dd(\Theme::get());` in your controller file...

Can you write again your output for `for {{ Theme::js('js/readmore.js')` - it was blank...

**Comment by rayhan0421** [comment]
i set this  \Theme::set('t1');   in middleware

**Comment by rayhan0421** [comment]
output   for dd(\Theme::get());  is   "t1"

**Comment by rayhan0421** [comment]
![jsssq](https://cloud.githubusercontent.com/assets/2592229/8551644/b5bc70e0-24f9-11e5-8c74-dcb819f3dc2e.PNG)

**Comment by igaster** [comment]
Resuming: 
- file `index.blade.php` exists in 'resources\view\t1'
- Your configuration is OK. 
- You have set theme to 't1'. You can chek it with `dd(\Theme::get());` in your controller.

This package rellies to Laravel viewFinder to discover the correct view from the paths. It should pick the correct one!

Be aware that laravel does not render your themes but it rather compiles them and renders the compiled file (for speed). You may encounter sittuations when you are editing your theme's views but Laravel does not recompile it and renders the last compiled file... Try to delete all compiled files in `storage\framework\views`...

**Comment by rayhan0421** [comment]
not working

**Comment by igaster** [comment]
Out of ideas... Can you please setup a sample project and email it me as an zipped archive? I'll be happy to inpect it for you further... my email is in my profile. Thank you.

**Comment by rayhan0421** [comment]
slash problem ?

![slash](https://cloud.githubusercontent.com/assets/2592229/8552048/3cd73f86-24fc-11e5-822c-f24803c1186d.PNG)

**Comment by rayhan0421** [comment]
do u have fb or twitter id

**Comment by igaster** [comment]
No, its ok in windows.. 

Check it out: `dd(file_exists(\Config::get('view.paths')[0].'index.blade.php'));`

twitter @mycorfuguide, I'll be back online in the next hours... Thanks

**Comment by rayhan0421** [comment]
i check dd(file_exists(\Config::get('view.paths')[0].'index.blade.php'));
and dd(file_exists(\Config::get('view.paths')[1].'index.blade.php'));

output false for two

**Comment by rayhan0421** [comment]
after run your demo app 
![demoapp](https://cloud.githubusercontent.com/assets/2592229/8552360/709ec2ba-24fe-11e5-8348-b84d303d5c60.PNG)

**Comment by rayhan0421** [comment]
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<link media="all" type="text/css" rel="stylesheet" href="/theme.css">

	</head>
	<body>
		<h1> Greetings from "DEFAULT" theme  </h1>
		<ul>
			<li> This is the "default" theme. </li>
			<li> All themes inherit the default theme. If an asset/view is not found in a theme then it will picked from this theme. </li>
			<li> This is an example of an image (located at: "/img\test.gif"): </li>
		</ul>
		<img src=/img\test.gif>

		<hr>
Switch to Theme:
<a href="setTheme/t1">t1</a> |
<a href="setTheme/t2">t2</a> |
<a href="setTheme/t3">t3</a> |
<a href="setTheme/Default">None</a>


<ul>
  <li>This links are defined in 'links.blade.php' which is located in the default theme.</li>
  <li>Since no other theme overides this view it is shared among all themes.</li>
</ul>

<hr>

To explore this project's source take a look at: | config\themes.php | routes.php | resources\views\... | public\... |

	</body>
</html>

**Comment by rayhan0421** [comment]
html source code

![demohtml](https://cloud.githubusercontent.com/assets/2592229/8552443/eaf7e1ea-24fe-11e5-9cf3-399b3b97351f.PNG)

**Comment by igaster** [comment]
File doesn't exists? This is the problem. Any idea? file capitalisation doesn't matter in windows... dows my demo app works fine? Please check the following:
 - How are you returning your view in your controller?
 - Are you including / extending views that doesn't exist?

**Comment by rayhan0421** [comment]
i am extending layout.blade.php file

**Comment by rayhan0421** [comment]
but i did it without extending layout  . did not work

**Comment by rayhan0421** [comment]
in controller 

 public function service()
   {
	// dd(\Theme::get());
	
   //  dd(file_exists(\Config::get('view.paths')[0].'welcome.blade.php'));
// dd(\Config::get('view.paths'));
  // $data['service'] = DB::table('service')->whereid(1)->first();       
  //return view('html.service',$data);
    return view('index');
    }

**Comment by igaster** [comment]
Please send me an archive of your project to inspect... it is a strane
issue...

Στις Τρί, 7 Ιουλ 2015 - 20:27 ο χρήστης Rayhan Uddin <
notifications@github.com> έγραψε:

**Comment by rayhan0421** [comment]
ok i am doing with fresh laravel project

**Comment by rayhan0421** [comment]
Sir its working but there one issue {!!Theme::css('css/style.css')!!} is return full path only https://cloud.githubusercontent.com/assets/2592229/8552443/eaf7e1ea-24fe-11e5-9cf3-399b3b97351f.PNG

**Comment by rayhan0421** [comment]
hello sir , how solve this above

**Comment by igaster** [comment]
You have been confused with the use of middleware.... It was just an example for the demo project. I've simplified more [here](http://we.tl/Bgh5v69UC4) without a middleware. Just open routes.php and set the theme at the beggining of the file (uncomment the lines). You will see that all paths are resolved correct. Depending on your implementation you might want to set the theme on a ServiceProvider, in a Middleware or even in your controller....

**Comment by rayhan0421** [comment]
output :
Path of style.css = "/t2/css/style.css"

Some view in "t2" theme... 

i want full path

**Comment by rayhan0421** [comment]
output like that http://laravel-recipes.com/recipes/184/generating-a-link-to-a-css-file

**Comment by rayhan0421** [comment]
it works if i do this in themes.php 

	public function css($href){
		
		$url = url().$this->url($href);
		
		return '<link media="all" type="text/css" rel="stylesheet" href="'.$url.'">'."\n";
	}

**Comment by rayhan0421** [comment]
any future problem

**Comment by rayhan0421** [comment]
hello sir

**Comment by igaster** [comment]
Theme::url() returns the relative path to your Domain. You should add your
domain manually on your blade - Or create a helper. Something like

{{url(Theme::url('my.css'))}}

For more info how to get your domain URL take a look here
<http://stackoverflow.com/questions/17201170/php-how-to-get-the-base-domain-url>.
I will consinder adding this functionality in future releases...

**Comment by rayhan0421** [comment]
thank u

**Comment by rayhan0421** [comment]
nice project
