### ISSUE TITLE
Call to a member function add() on string In Theme.php line 29:                                                 

### ISSUE THREAD

**Issue by astinaam** [igaster/laravel-theme#110]
Created using `php artisan theme:create theme_name`. After that its showing this error on every requests, artisan commands, composer commands.

In Theme.php line 29:
                                             
`  Call to a member function add() on string  `

Composer required :
```json
"igaster/laravel-theme": "^2.0",
"orchestra/asset": "~3.8",
"orchestra/support": "~3.8"
```

**Comment by igaster** [comment]
Hello @astinaam, can you post your stack trace of the error?
