### ISSUE TITLE
mkdir(): No such file or directory

### ISSUE THREAD

**Issue by ju5t** [igaster/laravel-theme#119]
In createTheme you're creating theme folders without setting recursive on makeDirectory. In my current setup (MacOs 10.14.6) this fails with:

```
ErrorException  : mkdir(): No such file or directory
```

I believe the fix for this to be:

```php
// Create Paths + copy theme.json
$this->files->makeDirectory($viewsPathFull, 0755, true);
$this->files->makeDirectory($assetPathFull, 0755, true);
```

I am more than happy to raise a PR if this is a bug or needs fixing. Let me know what you think.

**Comment by igaster** [comment]
Fixed with v2.0.14
