### ISSUE TITLE
Impossible to replace/override \igaster\laravelTheme\Themes class

### ISSUE THREAD

**Issue by blackakula** [igaster/laravel-theme#14]
In `themeServiceProvider::register` method 'igaster.themes' is bind as shared and instantly is used:
`$Themes = $this->app->make('igaster.themes');`. As a result, it's impossible to substitute `Themes` class. I suggest `themeServiceProvider::register` to do only registration job. All the themes crawling should be done later - before rendering with `$this->app['events']->listen('composing:*', $detectThemesCallback);` (this event will be called before any method from your `Themes` instance)

**Comment by igaster** [comment]
Not the best solution because the Theme facade would be unusable before views rendering has started (eg in the controllers). 

Sorry for the delayed reply... needed some time to evaluate it....
