### ISSUE TITLE
Remove line breaks for ::css(), ::js and ::img() ( \n )

### ISSUE THREAD

**Issue by TechKat** [igaster/laravel-theme#15]
There's really no need for them.

**Comment by igaster** [comment]
Makes html output more readable IMO...  I will consider it in next release.

Thanks for the feedback...

**Comment by TechKat** [comment]
The \n adds an extra empty line in the HTML output, which bothers me.

**Comment by igaster** [comment]
Will check it out!

**Comment by igaster** [comment]
ok, v1.0.14
