### ISSUE TITLE
Theme::css, js, img and url does not output

### ISSUE THREAD

**Issue by DanielRTRD** [igaster/laravel-theme#16]
Using Windows to develop. First of all; why does it compile as text and not as HTML? And why does it not get the URL correctly?

Log file:
```
[2015-10-22 20:04:14] local.WARNING: Asset not found [bootstrap.css] in Theme [neon]  
```

File structure:
![22-10-2015 20_05_29](https://cloud.githubusercontent.com/assets/9788214/10673896/7e21608e-78f8-11e5-9365-300267bf3405.png)

Code:
![22-10-2015 19_35_46](https://cloud.githubusercontent.com/assets/9788214/10673658/43ce9628-78f7-11e5-942e-ff05c04a4639.png)

Output:
![22-10-2015 19_35_32](https://cloud.githubusercontent.com/assets/9788214/10673657/43ccd93c-78f7-11e5-9295-3ef517e8ccc1.png)

Code 2:
![22-10-2015 19_53_41](https://cloud.githubusercontent.com/assets/9788214/10673656/43cab940-78f7-11e5-88c7-5520cdabdf52.png)

Output 2:
![22-10-2015 19_53_47](https://cloud.githubusercontent.com/assets/9788214/10673655/43ca91b8-78f7-11e5-8d47-e9824dd9e399.png)

Config file:
```php
<?php

return [

	'enabled' => true,

	'asset_not_found' => 'LOG_ERROR',

	'active' => 'neon',

	'themes' => [

		'bootstrapextended',

		'neon',

	],

];

```

**Comment by igaster** [comment]
1. When you are refering to local files all paths are relative to your theme folder. so the correct is:

    {{Theme::css("css/bootstrap.css")}}

or you can manually build your css/js/img links using:

    {{Theme::url("css/bootstrap.css")}}

try it!

2. Text vs HTML ? Sorry I don't understand. Please clarify...

**Comment by DanielRTRD** [comment]
It works fine when I add "css/" infront of the css file. But you should really hardcode that the css adds "css/", same for js and img.

It renders and text and not HTML. And the template is f'd up of some sort. Tried both a new theme and bootstrap.
![22-10-2015 22_56_30](https://cloud.githubusercontent.com/assets/9788214/10678083/63ff42b2-7910-11e5-8a25-eca336a496c5.png)
![22-10-2015 22_55_58](https://cloud.githubusercontent.com/assets/9788214/10678082/63fe80fc-7910-11e5-9e85-dcc653333ad1.png)

**Comment by askaoru** [comment]
IMO hardcoding 'css' directory it would make it harder. other people might use something like 'styles' or 'assets' instead of the generic css, so leaving it as is better.

**Comment by igaster** [comment]
Hardcoding paths will break many themes...

**Comment by DanielRTRD** [comment]
Yeah, I agree.

But what about the other problem?

**Comment by DanielRTRD** [comment]
It renders it as text and moves the rest of the header to under the body. Look:
![23-10-2015 21_15_29](https://cloud.githubusercontent.com/assets/9788214/10702657/6bc2d912-79cb-11e5-8660-76c2f073aaf0.png)
![23-10-2015 21_14_56](https://cloud.githubusercontent.com/assets/9788214/10702656/6bc1403e-79cb-11e5-981a-fd7c5fbbbc5a.png)

**Comment by DanielRTRD** [comment]
Any ideas on the problem?

**Comment by igaster** [comment]
It seems that your editor parses it as text or comment... I will review css output in the next release. Anyway you can generate any link using the general **Theme::url** function. ie:

    <link rel="stylesheet" href="{{Theme::url('css/bootstrap.min.css'}}"></link>

**Comment by DanielRTRD** [comment]
```{{ Theme::url('css/bootstrap.min.css') }}```
Works fine! :)
