### ISSUE TITLE
what about multi-language case ?

### ISSUE THREAD

**Issue by mikimaine** [igaster/laravel-theme#17]
what i want to say is there is no way to manage language assets of each theme .
for example like this 
```
       resources /
                        lang/
                                t1/
                                   en/
                                   fr/   
                                 t2/
                                   en/
                                   fr/
                        view/
                                t1/
                                t2/
```

**Comment by igaster** [comment]
String translation is handled natively by Laravel. However if you want to use different assets depending on current language you can set a custom key to a theme eg `Theme::configSet('lang', 'en')`, and use the curly brackets syntax to create paths using this key in Blade. eg:

    {{Theme::url('flag-{lang}.png}}

Hope this helps...
