### ISSUE TITLE
How do I access the views/assets of a parent theme?

### ISSUE THREAD

**Issue by extrakun** [igaster/laravel-theme#18]
It will be great if there's a way for us to access the parent theme views/assets; is there anyway to do so?

**Comment by igaster** [comment]
not out of the box... However you can access an instance of the parent Theme using:

    $parentTheme = Theme::find(Theme::get())->getParent();

and you can use the new theme to build your views. eg:

    $parentTheme->url('logo.png');

**Comment by igaster** [comment]
1. As for views NO. you have to switch to the parent Theme first. You can always get the parent theme name using `Theme::config('extends');`

2. As for the assets YES. You can get the parent Theme instance using:

        $parentTheme = Theme::find(Theme::config('extends'));

and build your views using $parentTheme. eg:

        $parentTheme->url('logo.png');
