### ISSUE TITLE
Laravel 5.2 compatibility

### ISSUE THREAD

**Issue by UnrulyNatives** [igaster/laravel-theme#19]
Hi, 
I just tried to upgrade to Laravel 5.2 and I got compatibility issue:

`igaster/laravel-theme v1.0.14 requires illuminate/support 5.0.*|5.1.*`

my composer.json contains `"illuminate/support": "5.*",`, so I am out of ideas.
Thx

**Comment by igaster** [comment]
check version 1.1

be aware that if you were using orchestra/asset you should read again the README because some dependencies have changed..

**Comment by UnrulyNatives** [comment]
thank you!
