### ISSUE TITLE
Nothing to publish for tag [].

### ISSUE THREAD

**Issue by dlepaux** [igaster/laravel-theme#20]
Hi,

When i publish config, like in README.md, i got this message and config is not published.

Thanks

**Comment by igaster** [comment]
I will check it out. Meanwhile you can try the generic
```
php artisan vendor:publish
```

**Comment by dlepaux** [comment]
Yes i know but i would like to find a nice way to deploy this package :)

I'm soory but i got this error when i do your command :  There are no commands defined in the "vendor" namespace.

I doesn't understood.. I put your package in 'packages' folder in root..

Thanks Igaster,

David

**Comment by igaster** [comment]
It seems that you haven't installed the package at all. You should: 1) install it through composer 2) Add the Service provider (which register's the artisan command) and THEN execute the artisan publish command...

**Comment by dlepaux** [comment]
I just add the repo with composer in `vendor` but the problem is persisting.. I havealways `Nothing to publish for tag [].`.

**Comment by igaster** [comment]
just tested it in L5.2 and woeks fine with me. Did you added the `igaster\laravelTheme\themeServiceProvider::class,` in your app.php? What Laravel version are you using?

**Comment by dlepaux** [comment]
Yes i added it in config/app.php and the alias too.

I have the version 5.2.7

**Comment by igaster** [comment]
Thanks @fishisawesome, it should be fixed in all environments now
