### ISSUE TITLE
Support overriding vendor packages views

### ISSUE THREAD

**Issue by JFossey** [igaster/laravel-theme#22]
I really like your theme package its simple and not overly complex compared to the others I have looked at.

I have a requirement to be able to override view files that are provided by custom packages.

I can publish the views to /resources/views/vendor but I can't seem to override the views from inside my theme.

I hacked at the themeViewFinder.php file and override the findNamedPathView() function and the below is the result that provides me this feature for me.

It would be great if support for this was added to your package.

```php
<?php namespace igaster\laravelTheme;

use Illuminate\View\FileViewFinder;
use Illuminate\Support\Arr;

class themeViewFinder extends FileViewFinder {

    /**
     * Add support for vendor namded path overrides.
     *
     * @param  string  $name
     * @return string
     */
    protected function findNamedPathView($name)
    {
        list($namespace, $view) = $this->getNamespaceSegments($name);

        $vendorPath = $this->paths[0] . '/vendor/' . $namespace;
        $hints = $this->hints[$namespace];

        if (!Arr::has($hints, $vendorPath)) {
            $this->hints[$namespace] = Arr::prepend($hints, $vendorPath);
        }

        return $this->findInPaths($view, $this->hints[$namespace]);
    }

	public function setPaths($paths){
		$this->paths = $paths;
	}

	public function test(){
		dd($this->paths);
	}

}
```

**Comment by igaster** [comment]
@JFossey thank you for your contribution. Please provide a usage scenario, so I could create some test cases before can I push it. Themmed packages, nice idea!

**Comment by JFossey** [comment]
The way I am using it is by creating custom reusable packages for common functionality that is needed in multiple projects.

For packages that will not be registered in a public repo like Github I created a separate packages folder/

```json
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Core\\": "packages/MyPackageName/src"
        },
}
``` 

Then under packages/MyPackageName/src I create a package or in sub folders sub packages depending on the requirements.

`packages/MyPackageName/src/MySubPackage`

Then in my package service provider I give my package views a vendor name space by adding a view hint.

```php
<?php
class ExampleServiceProvider extends ServiceProvider
{
    public function boot()
    {
        // Set Views path Hint for Custom Package
        $this->loadViewsFrom(__DIR__ . '/Views', 'MyExamples');
    }
}
```

Then I create my functionality with views in my package. 

The default way to override these packages views is to publish them to `/resources/views/vendor/ViewNameSpace`. Using the above example that would be `/resources/views/vendor/MyExamples`

```php
<?php
class ExampleServiceProvider extends ServiceProvider
{
    public function boot()
    {
        // Set Views path Hint for Custom Package
        $this->loadViewsFrom(__DIR__ . '/Views', 'MyExamples');

        // Publish Package Views
        $this->publishes([
            __DIR__ . '/Views' => base_path('resources/views/vendor/MyExamples'),
        ], 'views');
    }
}
```

The problem is that I can only override these views once in my global views folder and this negates the use and power of themes.

With the provided patch I am able to create a folder in my theme views folder called vendor/ViewNameSpace and override view files per a theme.

Using the above example I am able to have the following:

`resources/views/themes/myZurbTheme/views/vendor/MyExample/`

Another benefit is related to third party packages. As I like to use Zurb Foundation but most packages seem to favor Bootstrap, with this patch I am able to override Boostrap templates in my themes.

I hope that helps explain the use of this patch better.

**Comment by igaster** [comment]
v1.1.1 (Laravel 5.2)

**Comment by hailwood** [comment]
@igaster - shouldn't this issue be closed now?
