### ISSUE TITLE
View not found

### ISSUE THREAD

**Issue by younes0** [igaster/laravel-theme#33]
Using laravel 5.2, and laravel-theme dev-master or 1.1, I've tried to `View::make('test')` (no layout inheritance)
```
resources/themes/mytheme/test.blade.php
resources/themes/mytheme/views/test.blade.php
views/themes/mytheme/test.blade.php
views/themes/mytheme/views/test.blade.php
```
But I get view file is not found, with `view:clear` everytime

config.php is
````php

'active' => 'pixeladmin',

// tried:
'themes_path' => null, // or
'themes_path' => realpath(base_path('resources/themes')), // or
'themes_path' => realpath(base_path('resources/views')),

'themes' => [
	'pixeladmin', // or
        'pixeladmin' = [
              'views-path' => '' // or
              'views-path' => 'resources/themes/pixeladmin/',
        ],
]
```
What am I doing wrong please :( ?

**Comment by igaster** [comment]
It seems that you have placed your views in a "mytheme' folder which is not configured correctly. For example for the following path:


```
resources/themes/mytheme/test.blade.php
```

the correct configuration would be:

```php
'active' => 'pixeladmin',

'themes_path' => realpath(base_path('resources/themes')),

'themes' => [
        'pixeladmin' = [
              'views-path' => 'mytheme',
        ],
]
```
Or you can simply rename the theme folder to match the theme name ('pixeladmin') and you would not need to configure the 'views-path'

hope this helps!

**Comment by younes0** [comment]
Thanks for your help. Couldn't make it work though...
