### ISSUE TITLE
Package is not working on Laravel 5.3

### ISSUE THREAD

**Issue by dcdiogo** [igaster/laravel-theme#43]
Dear,

When I tried to use this package on Laravel 5.3, the command **php artisan optimize** fails with the error:
`Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\View\FileViewFinder::setPaths()
`
On Laravel 5.2 it works fine.

By the way, greate package! Very usefull!.

Regards,
Diogo

**Comment by igaster** [comment]
This package uses themeViewFinder.php (which extends Illuminate\View\FileViewFinder). All setup takes place at the `themeServiceProvider.php`. So my guess is that either

a) you forgot to add the service provider & alias at your `app/config/app.php` file

or 

b) sometimes the order that you put your service providers does matter! Try to place the `themeServiceProvider` lower (Certainly after all `Illuminate/xxx` service providers)

**Comment by Jeroen-G** [comment]
Or c) the function is no more.

**Comment by igaster** [comment]
It is actually defined here: [themeViewFinder.php](https://github.com/igaster/laravel-theme/blob/master/src/themeViewFinder.php)

Can you please verify that the latest version of the package has been installed? (v1.1.3)

Maybe an error on composer.json ?

**Comment by Jeroen-G** [comment]
Ah, I was looking for that function in FileViewFinder
