### ISSUE TITLE
can't get it to work with laravel 5.3

### ISSUE THREAD

**Issue by nermion** [igaster/laravel-theme#44]
I just found this package and I am using laravel 5.3

I installed the package, published the config file which I did not modify, modified app.php according to instructions. Created theme named default inside resources/views and put index.blade.php inside theme folder.

In my controller I did this:

        Theme::set('default');
        $categories = Category::with('children')->parents()->orderBy('created_at', 'asc')->paginate(100);
        return view('index', compact('categories'));

when I hit that specific route in the browser I get the error

InvalidArgumentException in FileViewFinder.php line 137: View [index] not found. but the index is right there in the default folder. What could I be doing wrong?

**Comment by igaster** [comment]
Hi!

This is normal as the "default" theme is configured to match Laravel's default paths (ie **\resources\views** and  **\public**)

If you want to setup a quick test-theme you can

a) add to your themes.php (under  the "default" theme):

```php
'myTheme' => [
	'views-path' 	=> 'myTheme',
	'asset-path' 	=> 'myTheme',
],
```

b) put your views at **resources\views\myTheme**
c) put your public assets at **public\myTheme**

**Comment by nermion** [comment]
yeah I figured it out, what confused me was this part: 

    | 		'views-path' 	=> 'path-to-views',    // defaults to: resources/views/theme-name
    | 		'asset-path' 	=> 'path-to-assets',   // defaults to: public/theme-name

maybe you should remove or update that to say that it defaults to nothing and that we need to set it to something?

**Comment by nermion** [comment]
and thanks for making the great package, out of 4-5 laravel themes packages I choosed yours since it was the best

**Comment by igaster** [comment]
:-) Hadn't ever thought of this interpretation!

I suppose that this would easier to grasp:
> ...defaults to "blah blah" except for the default theme which defaults to laravel's defaults
LOL

I promise I'll try to clear it down on the next update! 

Thanks for your nice words!
