### ISSUE TITLE
how to  auto load view 

### ISSUE THREAD

**Issue by rajaee-rad** [igaster/laravel-theme#45]
I use laravel 5.2 and igaster/laravel-theme package.

when i want return view use below code 

      public function index()
        {
    
            return view('themes/' . Theme::get() . '/views.index');
        }
and load automatically default theme
But I prefer use this code

    return view('index');

structure folder:
resources
--------views
-----------------------theme1
-----------------------theme2

**Comment by haideritx** [comment]
i believe you need to set the Theme first.
I am my self new to this package. I read the documentation, and sadly there was not mentioned anywhere the usage for it in controllers, but looking in to the issues of others figured out you can set the theme, and use the same old laravel way of calling your views.

And this worked for me.


```
Route::get('/', function () {
    Theme::set('lbcDefault');
    return view('welcome');
//    return \Igaster\LaravelTheme\Facades\Theme::url('welcome');
});
```

**Comment by igaster** [comment]
Yes you need to set the theme before you return a view!

Controller method is a valid place. It can also be inside a middleware, a
ServiceProvider etc...

Στις Παρ, 19 Οκτ 2018, 12:02 ο χρήστης Syed Haider Hassan <
notifications@github.com> έγραψε:
