### ISSUE TITLE
question about compability with modules package

### ISSUE THREAD

**Issue by nermamax** [igaster/laravel-theme#50]
Hi

What will happen if I use package that gives me modules, for example: https://github.com/caffeinated/modules/

this package gives modules it's own resource, that is stored in the module folder:

    'Resources/Views'   => 'resources/views',

What will happen when I try to use a view in the module resource folder, will laravel-theme package look in the wrong folder or will it load the view from modules folder?

Second question, since I would like modules to use the current theme layout how would I do that? Right now in my theme for any view I do this

    @extends('layouts.admin')

How would I do something like that with resource in the module folder, so that it finds the layout.blade.php of the current theme?

These question are important since I am building a CMS and would like to use modules package to enable development by others of "extensions" I do not want to use packages as way of making extensions since I want enduser who is not advanced to be able to install the extensions with a click and also since I plan to support shared hosting composer and packages are out of question.

Hope to get an answer, possibly from @igaster

**Comment by igaster** [comment]
This package ovverides the ViewFinder class from Laravel Framework so that it prepends the themes paths to the default laravel view paths, which are defined in views.php config file. Any package that ovverides this behaviour will conflict with Laravel Themes. 

Caffeinated uses a namespace::viewname approach which **might be** combatible with this package, however without testing it I can not tell. It also supports [remaping all paths](https://github.com/caffeinated/modules/wiki/Configuration#restructure-your-modules)...

**Comment by nermamax** [comment]
Good to hear, what about when I use @extends('layout.admin') your package has nothing to do with that, correct? So for the view file inside of module/resources/view to have @extends('layout.admin') that would mean that it would only look for layout/admin.blade.php inside the views folder in the module. To have it look in the current theme folder would that mean I would have to reimplement or override that blade directive?

**Comment by nermamax** [comment]
How about this, instead of messing with extends directive which may not even be possible, create a new directive lets call it @layout directive and inside that directive check for current theme path and and then look up correct layout to extend from, would that be a good idea?

**Comment by igaster** [comment]
Both **@extends** and the new **@component** directives rely to laravel `Illuminate\View\FileViewFinder` to discover the correct view in various location. This package actually ovverides this class with  [themeViewFinder.php](https://github.com/igaster/laravel-theme/blob/master/src/themeViewFinder.php) to add the various theme paths...This class provides a public setPaths() method which allows you to set the search locations...
If you want to explore how paths are build for the themes check the [Theme::set()](https://github.com/igaster/laravel-theme/blob/master/src/Themes.php#L59) method...
