### ISSUE TITLE
Runtime change theme extends value

### ISSUE THREAD

**Issue by grudge61** [igaster/laravel-theme#52]
Is it possible to change theme extends value at runtime?

I tried this way:
`Config::set('themes.themes.mobile.extends', 'new_theme_to_extend');`

but nothing happens..

Here a piece of my code where I need this..

```
if (Agent::isMobile()) {
    if (Portal::hasCustomMobileTheme) {
        Theme::set('mobile_' . Portal::getCustomTheme);
    } else {
        Config::set('themes.themes.mobile.extends', Portal::getCustomTheme);
        Theme::set('mobile');
    }
} else {
    Theme::set('default');
}
```

Default extends mobile theme value is default.

Hope if someone can help..
Thanks in advance

**Comment by igaster** [comment]
Hello,

Might be too late to answer but feature was added in latest version v2.x. You can:

Theme::find('theme-name')->setParent(Theme::find('parent-theme-name'));
