### ISSUE TITLE
Theme inherits defaults theme's path

### ISSUE THREAD

**Issue by DanielRTRD** [igaster/laravel-theme#53]
![2017-05-16 18_38_19](https://cloud.githubusercontent.com/assets/9788214/26117552/3fa56d96-3a67-11e7-9c3e-76bf3865b133.png)

For some reason, after upgrading to 5.4 and updating this package to 1.14, this happens. It adds the default theme to the start if another theme is selected. Why?
```
<?php

return [

	'enabled' => true,

	'themes_path' => null,

	'asset_not_found' => 'LOG_ERROR',

	'active' => 'frontend',

	'themes' => [

		'bootstrapextended',

		'frontend',

		'neon-admin',

		'neon-user',

	],

];
```

**Comment by danstreeter** [comment]
I'm getting this too - haven't delved deep enough into the package or Laravels internals to figure out why yet but have got around it by defining my theme path a little more 'absoute' in the config file:

<img width="747" alt="screen shot 2017-05-28 at 18 00 46" src="https://cloud.githubusercontent.com/assets/20464844/26530594/cbf70e0a-43cf-11e7-99ab-25a68968708f.png">

**Comment by igaster** [comment]
Hello I've tried to reproduce the issue but in my setup everything seems to be fine... I used @DanielRTRD configuration file and got a normal error:

    InvalidArgumentException in FileViewFinder.php line 137:
    View [tests] not found.
    in FileViewFinder.php line 137
    at FileViewFinder->findInPaths('tests', array('/home/vagrant/Code/smarthotels/resources/views/neon-admin', '/home/vagrant/Code/smarthotels/resources/views')) in FileViewFinder.php line 79

Can you share some additional information? Where are you setting your theme? (Controller? Service Provider? Middleware?)

You can update to latest version v1.15 first so that we will have the same installation...

**Comment by DanielRTRD** [comment]
I used a provider to set the theme.

Updating to 1.15 solves the problem!

**Comment by DanielRTRD** [comment]
This problem popped up again while I was merging branch.

Provider file:
`<?php namespace LANMS\Providers;

use Illuminate\Support\ServiceProvider;

class ThemeSelectServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap the application services.
	 *
	 * @return void
	 */
	public function boot()
	{
		if (\Request::segment(1)=='admin') {
			\Theme::set('neon-admin');
		}

		if (\Request::segment(1)=='user') {
			\Theme::set('neon-user');
		}

		if (\Request::segment(1)=='account' && \Request::segment(2)=='register' || \Request::segment(2)=='login' || \Request::segment(2)=='forgot' || \Request::segment(2)=='recover' || \Request::segment(2)=='activate' || \Request::segment(2)=='resetpassword') {
			\Theme::set('neon-user');
		}
	}

	/**
	 * Register the application services.
	 *
	 * @return void
	 */
	public function register()
	{
		//
	}

}
`

Config:
`<?php

return [

	'enabled' => true,

    'themes_path' => null, 

	'asset_not_found' => 'LOG_ERROR',

	'active' => 'frontend',

	'themes' => [

		'bootstrapextended',

		'frontend',

		'neon-admin',

		'neon-user',

	],

];
`

**Comment by igaster** [comment]
Hello, v2.x has been published. If you upgrade you may check again if the problem persists...

Requires L5.4
