### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by jhourlad** [igaster/laravel-theme#54]
The library seems to hide URLS of assets if not found in the hierarchy. This prevents the developer from debugging the code. Any workaround on this?

**Comment by igaster** [comment]
Yes!

Publish the configuration file and change the value of 

    'asset_not_found' => 'LOG_ERROR',

to

    'asset_not_found' => 'THROW_EXCEPTION',

**Comment by jhourlad** [comment]
It works! Thank you.
