### ISSUE TITLE
syntax error, unexpected 'list' (T_LIST),

### ISSUE THREAD

**Issue by meiwentiya** [igaster/laravel-theme#59]
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in src/Themes.php on line 35

**Comment by tsaiyihua** [comment]
I also has this issue, it happened on PHP 5.6 but PHP 7.0

**Comment by igaster** [comment]
PHP 5.x doesn't allow a list() method to be defined in a class and throws an error. PHP 7 is less restrictive...
I will rename this function in the next update, 1-2 days max...

Thank you for spotting it

**Comment by igaster** [comment]
Should be fixed in v2.0.3!
