### ISSUE TITLE
Theme::url() assumes webroot is /public/

### ISSUE THREAD

**Issue by TheDigitalOrchard** [igaster/laravel-theme#6]
Laravel is distributed with a default webroot folder called /public/ within its file structure, but that is not compatible with all web servers. Some servers will have a webroot in a different location, such as /public_html/ on cPanel servers.

Theme::url() makes an assumption that Laravel's /public/ folder is the webroot, and therefore fails to find assets when the webroot is located somewhere else. One workaround could be to compose the path using $_SERVER['DOCUMENT_ROOT'] as the base.

**Comment by igaster** [comment]
fixed in v1.0.12
