### ISSUE TITLE
Feature Request: Lang and Config files theme override

### ISSUE THREAD

**Issue by MikeMnD** [igaster/laravel-theme#65]
Pretty often lang and config have some subtle changes from theme to theme and such a feature will be very usefull out of the box.

At the moment this is the solution with the lang files:
https://laracasts.com/discuss/channels/laravel/dynamically-overrideextend-language-files

And still picking the right way for the config files

**Comment by UnrulyNatives** [comment]
+1

**Comment by MikeMnD** [comment]
Closing this cause I dont like to see it in my issues 🗡️
