### ISSUE TITLE
Error on creating new theme using artisan command

### ISSUE THREAD

**Issue by phardnor** [igaster/laravel-theme#66]
Hi, @igaster thank you for this package. I would like to ask about the issue below. This is a fresh install **laravel 5.4** and **laravel-theme 2.0**. I followed the installation and creating a new theme in your doc but an error occurred below. Any suggestions?

PHP Version: 5.6.*

`C:\xampp\htdocs\advanced-user-management>php artisan theme:create

 Give theme name::
 > Theme1

 Where will views be located [Default='Theme1']?:
 > Theme1

 Where will assets be located [Default='Theme1']?:
 > Theme1

 Extends an other theme? (yes/no) [no]:
 > n

Summary:
- Theme name: Theme1
- Views Path: C:\xampp\htdocs\advanced-user-management\resources\views/Theme1
- Asset Path: C:\xampp\htdocs\advanced-user-management\public\Theme1
- Extends Theme: No

 Create Theme? (yes/no) [yes]:
 > y

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected 'unset' (T_UNSET), expecting identifier (T_STRING)`

Thank you. Appreciated your response!

**Comment by igaster** [comment]
It could be a PHP 5.x compability issue - I am developing in v7.x. 
What is your PHP version? I will run some tests in previous version to ensure that there are no conflicts...

**Comment by phardnor** [comment]
My current version is 5.6.*. I hope you will support 5.x+. 

Thank you.

**Comment by igaster** [comment]
Fixed in v2.0.3. Please check!

**Comment by phardnor** [comment]
Working now. Thank you.
