### ISSUE TITLE
issue with laravel-5.5 `call_user_func_array() expects parameter 1 to be a valid callback`

### ISSUE THREAD

**Issue by UnrulyNatives** [igaster/laravel-theme#70]
I have the Laravel 5.5 and the latest version of this package successfully added.

## Problem
As soon as I add my first theme by :

`'default' => 'bootstrap',`

and

```
		'bootstrap' => [
			'extends'	 	=> null, 
		],
```

I receive the error

`call_user_func_array() expects parameter 1 to be a valid callback, class 'Igaster\LaravelTheme\Theme' does not have a method 'config' (View: \resources\views\pages\create.blade.php)`

I tried several variants but to no positive result.

Thx.

**Comment by igaster** [comment]
It seems that you have upgraded from package version v1.x to v2.x. The config() method has been renamed to getSetting(). Check the [Migration Guide](https://github.com/igaster/laravel-theme/wiki/Migrating-from-v1.x#3-themeconfig--themeconfigset)
