### ISSUE TITLE
Theme::css not working

### ISSUE THREAD

**Issue by dyanakiev** [igaster/laravel-theme#81]
Hello,
Im using 1.16.0 with laravel 5.4

```
<?php

return [
    'enabled' => true,
    'themes_path' => realpath(base_path('resources/themes')),
    'asset_not_found' => 'LOG_ERROR',
    'active' => 'gameservers',

    'themes' => [
        'gameservers' => [
            'extends'       => null,
            'views-path'    => 'spark',
            'asset-path'    => 'themes/spark',
        ],
    ],
];
```
This is my config/themes.php

Line from logs:
```
[2018-01-06 16:46:58] development.WARNING: Asset not found [css/spark.css] in Theme [spark]  
```
But there are files..

What i miss?

**Comment by igaster** [comment]
There is no 'spark' theme defined in your configuration. Your theme is named 'gameservers' (it is the key on the associative array). If you fix it then it will probably locate your files...

A quick note: Assets are always located inside the public folder. According to your configuration you file should be located at  `public/themes/spark/css/spark.css`. (On linux servers it is also case sensitive)

**Comment by dyanakiev** [comment]
Oh i changed it for the example and forgot to change it above.

Oh stupid me, i was missing character in the real folder name...

Thanks, problem solved :D
