### ISSUE TITLE
The url function doesn't care about possible base_url config

### ISSUE THREAD

**Issue by etshy** [igaster/laravel-theme#82]
I'm working on a dev server, so I use subfoder in www/html folder to test my apps.
So my laravel app are in /var/www/html/laravel_app and I acces by http://myserverip/laravel_app/

As the theme class > url function don't take the base_url (config set in both app.php config file) it try to load /content/themes/... instead of /laravel_app/content/themes/...

classic url() function in Laravel works great with my subfolder, only files not loaded are from the themes folder.

**Comment by igaster** [comment]
That is a tricky config.

Your problem lies with theme views or with theme assets?

**Comment by etshy** [comment]
It was with theme assets
when I called Theme::url() in my layout it doesn't return the host/subfolder, only the them path, starting with '/content/theme' etc.

**Comment by kavin-90** [comment]
same here

theme_url return /css/style,css that i wrote in theme_url("/css/style,css") function :(

**Comment by igaster** [comment]
The problem is that the package will return the relative URL to document root, because defininf the 'url' parameter at the app.php configuration file is optional.

You may wrap it with laravel `url()` function to get the full URL:

` url(theme_url('file1.txt'));`
