### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by appdezign** [igaster/laravel-theme#85]
When I try to upgrade to Laravel 5.6, I get an error because of a dependency in laravel-theme:

"require": {
        "illuminate/contracts": "5.4.*|5.5.*"
},
`

**Comment by igaster** [comment]
Hello, I will upgrade it today!

**Comment by igaster** [comment]
Fixed. It will grab v2.0.6+ for Laravel 5.6 now
