### ISSUE TITLE
Create Theme File Already Exists

### ISSUE THREAD

**Issue by jeremy0613** [igaster/laravel-theme#88]
Laravel 5.4
Artisan 5.6.7

php artisan theme:create

Theme is trying to create the views folder resources/views but it already exists.
The code output suggests that force will jump past this however, when I attempt to use --force Symfony is throwing the exception that --force is not an option.

php artisan theme:create -v --force

438|         if ($force) {
    439|             return @mkdir($path, $mode, $recursive);
    440|         }
    441| 
  > 442|         return mkdir($path, $mode, $recursive);
    443|     }
    444| 
    445|     /**
    446|      * Move a directory.

In ArgvInput.php line 217:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--force" option does not exist.                    
                                                          

Exception trace:
 Symfony\Component\Console\Input\ArgvInput->addLongOption() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Input/ArgvInput.php:153
 Symfony\Component\Console\Input\ArgvInput->parseLongOption() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Input/ArgvInput.php:82
 Symfony\Component\Console\Input\ArgvInput->parse() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Input/Input.php:55
 Symfony\Component\Console\Input\Input->bind() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Command/Command.php:210
 Symfony\Component\Console\Command\Command->run() at /Applications/MAMP/htdocs/connect/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Application.php:241
 Symfony\Component\Console\Application->doRun() at /Applications/MAMP/htdocs/connect/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /Applications/MAMP/htdocs/connect/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /Applications/MAMP/htdocs/connect/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /Applications/MAMP/htdocs/connect/artisan:37

**Comment by enesyurtlu** [comment]
I faced with this error. And solves that. When it asks for assets and views folder, you should write a name. Otherwise it is trying to create views folder. When you entered a folder name it creates successfully.

**Comment by igaster** [comment]
Hello, fixed in latest commit.
