### ISSUE TITLE
İaravel 5.6  ErrorException  : mkdir(): File exists

### ISSUE THREAD

**Issue by fofotara** [igaster/laravel-theme#90]
Laravel 5.6 theme create error;
 ErrorException  : mkdir(): File exists

 ErrorException  : mkdir(): File exists

  at /Users/s-ahmet/Projeler/castistanbul.test/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php: 442
          if ($force) {
          return @mkdir($path, $mode, $recursive);
        }

       return mkdir($path, $mode, $recursive);
   }

   /**
    * Move a directory.

  Exception trace:

  1   mkdir("/Users/s-ahmet/Projeler/castistanbul.test/resources/views")
      /Users/s-ahmet/Projeler/castistanbul.test/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php : 442

  2   Illuminate\Filesystem\Filesystem::makeDirectory("/Users/s-ahmet/Projeler/castistanbul.test/resources/views")
      /Users/s-ahmet/Projeler/castistanbul.test/vendor/igaster/laravel-theme/src/Commands/createTheme.php : 71

  Please use the argument -v to see more details.

**Comment by igaster** [comment]
It seems that you are trying to use a theme name that aleady exists. Can
you check if there is a folder with the same name in your views folder?

**Comment by xbust3r** [comment]
i have the same error with laravel 5.6, and this is the first time which used igaster:

Create Theme? (yes/no) [yes]:
 >


   ErrorException  : mkdir(): File exists

  at C:\Users\PC1\servers\Homestead\www\enchantress\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:442
    438|         if ($force) {
    439|             return @mkdir($path, $mode, $recursive);
    440|         }
    441|
  > 442|         return mkdir($path, $mode, $recursive);
    443|     }
    444|
    445|     /**
    446|      * Move a directory.

  Exception trace:

  1   mkdir("C:\Users\PC1\servers\Homestead\www\enchantress\resources\views")
      C:\Users\PC1\servers\Homestead\www\enchantress\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:442

  2   Illuminate\Filesystem\Filesystem::makeDirectory("C:\Users\PC1\servers\Homestead\www\enchantress\resources\views")
      C:\Users\PC1\servers\Homestead\www\enchantress\vendor\igaster\laravel-theme\src\Commands\createTheme.php:71

  Please use the argument -v to see more details.

**Comment by enesyurtlu** [comment]
I faced with this error. And solved that. When it asks for assets and views folder, you should write a name. Otherwise it is trying to create views folder. When you entered a folder name it creates successfully.

**Comment by igaster** [comment]
Thank you for your feedback.. I will make some checks there...

**Comment by enesyurtlu** [comment]
And i edited some section to use it.
Folder structure I am using:
`
-baseroot;
--themes
---themename (this folder contains blade files and assets folder)
----assets (compiled css, images, js files)
----resources (uncompiled vuejs, sass files)
`
I think this is the best usage for theming. Like wordpress theming.

**Comment by pitylee** [comment]
@enesyurtlu How did you exactly changed the assets from /public/assets to /themes/my-theme/assets?

**Comment by enesyurtlu** [comment]
Edited lots of rows in library. I can share it with you, if you want.

**Comment by igaster** [comment]
@enesyurtlu <https://github.com/enesyurtlu> this means that the whole
theme (views+assets) must be placed inside the public path, right?

**Comment by enesyurtlu** [comment]
No. It is located in base path. not public directory.

**Comment by vladimir454** [comment]
lmao, your root direction is wrong

**Comment by igaster** [comment]
@vladimir454 ??
