### ISSUE TITLE
Asset not found

### ISSUE THREAD

**Issue by rafailml** [igaster/laravel-theme#92]
Hi guys,
I'm getting:
```
local.WARNING: Asset not found [js/app.js] in Theme [new_theme]
```
And I'm sure that app.js is in public/new_theme/js
In my view I've set: 
```
{!! Theme::css("css/app.css") !!}
```
and in browser I'm getting:
```
<link media="all" type="text/css" rel="stylesheet" href="">
```
And this works fine:
```
<link href="{{ asset('new_theme/css/app.css') }}" rel="stylesheet">
```

Can someone help me to debug that?

**Comment by igaster** [comment]
Hello @rafailml ,

Can you confrim that there is no typo there:

`{!! Theme::css("css/app.css") !!}` should be `{!! Theme::js("js/app.js") !!}`

**Comment by rafailml** [comment]
Hi @igaster,
there is no typo. I want to get css. But js does not work either.

**Comment by ricardovigatti** [comment]
This is probably caused by some server issue, like shared hosting.
