### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by nabeelio** [igaster/laravel-theme#96]
```
igaster/laravel-theme v2.0.7 requires illuminate/contracts 5.4.*|5.5.*|5.6.*
```

**Comment by timopaul** [comment]
have the same problem. is there already a solution for this?

**Comment by igaster** [comment]
Hello,
I need to test it with a fresh installation of L5.7 but I don't expect to find any problems.

If you wish to try it then you may (temporary) switch to the dev version with
```
igaster/laravel-theme": "dev-master@dev",
```

Also you might need to set
```
    "minimum-stability": "dev",
    "prefer-stable": true
```
It is OK, this will still pick the stable versions

**Comment by igaster** [comment]
Hello, support for L5.7 is now on latest stable version! You may ignore my previous message.

Thank you!
