### ISSUE TITLE
Cannot use Igaster\LaravelTheme\Facades\Theme as Themes because the name is already in use

### ISSUE THREAD

**Issue by kusumahendra** [igaster/laravel-theme#97]
i experienced this error on windows, but not on my mac.
any idea? Thanks

(1/1) FatalErrorException
Cannot use Igaster\LaravelTheme\Facades\Theme as Themes because the name is already in use

![screenshot_46](https://user-images.githubusercontent.com/2751443/45407710-dfc23400-b69c-11e8-8d95-69966b20323e.png)

**Comment by majost-colombia** [comment]
I have the same problem on windows, some have any idea?

**Comment by majost-colombia** [comment]
The error appear when after use php artisan theme:create, the first time the wizard run correctly, when i try execute this again the error appear.

**Comment by majost-colombia** [comment]
@igaster Pls a hand, i'm very confused about it. Thanks in advance.

**Comment by ionutgrecu** [comment]
Hi.
For laravel 5.4.* just use the version 2.0.6 and do not update it until the author will release a fix for this version of laravel.
In composer.json : "igaster/laravel-theme": "2.0.6",
Then in cli: composer update
