### ISSUE TITLE
default theme

### ISSUE THREAD

**Issue by robov** [igaster/laravel-theme#99]
What is the best and easiest way to set the default theme hardcoded to one of the available themes ?
so that if I do not specify a theme it will get the default one.
This will clean up my resources/views files really nicely with only themes.

I could do it by hard setting the session variable, but I rather have it outside of the session
Any suggestions ?

**Comment by robov** [comment]
Ok, got it... sorry for asking..
I created a new service provider and did there a `\theme::set`

**Comment by igaster** [comment]
Exactly!
